apiVersion: v1
kind: Pod
metadata:
  labels:
    lbl: demo
  name: sample
spec:
  containers:
  - name: sample
    image: ghcr.io/trion-development/echoserver:2
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        cpu: 100m
        memory: 64Mi
