apiVersion: v1
kind: Pod
metadata:
  labels:
    run: demo
  name: demo
spec:
  containers:
  - env:
    - name: foo
      value: bar
    image: ghcr.io/trion-development/echoserver:2
    name: demo
    ports:
    - containerPort: 3000

